<h1><center>DS 200 - Lab 1 NumPy

### Introduciton: 
This lab gives you practice on: 1) creating ndarrays; 2) ndarray indexing and slicing; and 3) ndarray operations. Simply follow along the instructions and regenerate the given results.

### Part I: Numpy Indexing and Slicing (50 points)

#### Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [160]:
# Run this line to have numpy in your workspace
import numpy as np

In [161]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Q1: Use ndarray indexing/slicing to reproduce the output of the cell below.

In [162]:
mat[2:,1:] 



array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### Q2: Use ndarray indexing/slicing to reproduce the output of the cell below. 

In [163]:
mat[3][4]



20

#### Q3: Use ndarray indexing/slicing to reproduce the output of the cell below. 

In [164]:
mat[[0,4]][:,[0,4]]



array([[ 1,  5],
       [21, 25]])

#### Q4: Use ndarray indexing/slicing to reproduce the output of the cell below. 

In [165]:
mat[[3,4]][:,[1,3]]



array([[17, 19],
       [22, 24]])

#### Q5: Get the summation of all numbers for each column. 

In [166]:
np.sum(mat, axis = 0)



array([55, 60, 65, 70, 75])

#### Q6: Get the standard deviation for each row. 

In [167]:
np.std(mat, axis = 1)



array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

#### Q7: Given the new ndarray `weight` as the weight (importance) of each column. Find the weighted average for each row.

In [168]:
weight = np.array([0.1, 0.1, 0.2, 0.2, 0.4])
weight

array([0.1, 0.1, 0.2, 0.2, 0.4])

In [169]:
mat.dot(weight)



array([ 3.7,  8.7, 13.7, 18.7, 23.7])

#### Q8: Re-order the numbers in each column in descending order.

Hint: in `arr[start:stop:stride]`, if the `stride` number is `-1`, numpy will slice the array backwardly. 

In [170]:
np.sort(mat)[::-1]



array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

#### Q9: Given a new ndarray, use boolean selection to extract all numbers that fall into a given number range [4, 8] (all inclusive). 

In [171]:
arr_10 = np.array([5, 6, 3, 2, 1, 8, 10, 4, 9, 7, 6])

In [172]:
arr_10_new = arr_10[(arr_10 > 3) & (arr_10 < 9)]



arr_10_new

array([5, 6, 8, 4, 7, 6])

#### Q10: Now, convert the vector `arr_10_new` from Q9 to a 2x3 matrix, and then sort the numbers in each column in ascending order.

In [173]:
arr_reshaped = arr_10_new.reshape(2, 3)


arr_reshaped

array([[5, 6, 8],
       [4, 7, 6]])

In [174]:
arr_sorted = np.sort(arr_reshaped, axis = 0)


arr_sorted

array([[4, 6, 6],
       [5, 7, 8]])

### Part II: Numpy in Practice (50 Points)
#### Given a dataset called 'iris.data' that represents three kinds of iris flowers. Execute the next two cells of code to load the given dataset into a Numpy array named `iris`. Follow along the rest of the instructions to answer each question. 

#### Meanings to the columns in the `iris` array:
1. Column 0: iris sepal length
2. Column 1: iris sepal width
3. Column 2: iris petal length
4. Column 3: iris petal width
5. Column 4: iris flower type (all NaNs)

In [175]:
data_url = 'https://raw.githubusercontent.com/BlueJayADAL/DS200/master/datasets/iris.data'

In [176]:
# Read in the data as float into an ndarray name 'iris'
iris = np.genfromtxt(data_url, delimiter=',', dtype='float')
iris

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

#### Q11 (10 points): Caculate the mean and standard deviation for column 0 (iris sepal length).
Hint: don't forget to use the axis parameter in ufunc. 

In [177]:
# Mean
mu = np.mean(iris[:,:1])


# Standard deviation
sd = np.std(iris[:,:1])


# Print them all
print(mu, sd)

5.843333333333334 0.8253012917851409


#### Q12 (20 points): Create a normalized form of iris's sepal length (column 0).  The new sepal length values should fall into the range between 0 and 1 after applying the normalization. 

#### The equation for normalization is:

\begin{equation*}
f(X) = \frac{X - Xmin}{Xmax - Xmin}
\end{equation*}

#### where `X` stands for a single observation from column 0, `Xmin` for the minimum observation, `Xmax` for the maximum observation, and `f(x)` for the normalized result. 

#### Firstly, select only the data from column 0 and name it to `sepal`.

In [178]:
sepal = iris[:,:1]


sepal = sepal.reshape(150,)
sepal

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

#### Then calculate the minimal and maximum observations of the `sepal` vector.

In [179]:
# Minimum sepal observation
smin = np.min(sepal)


smin

4.3

In [180]:
# Maximum sepal observation
smax = np.max(sepal)


smax

7.9

#### Lastly, calculate the normalized 'sepal' vector with the equation given above, and print it out.

In [181]:
# Sepal column after normalization
norm = (sepal-smin)/(smax-smin)

print (norm)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

#### Q13 (10 points): Use boolean selection to filter the data entries in the `iris` array, such that they must have petal length (column 2) > 1.0 and sepal length (column 0) < 4.5

In [182]:
iris[(iris[:, 0]> 1.0) & (iris[:, 0] < 4.5)]




array([[4.4, 2.9, 1.4, 0.2, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [4.4, 3. , 1.3, 0.2, nan],
       [4.4, 3.2, 1.3, 0.2, nan]])

#### Q14 (10 points): The softmax function is a widely used normalization function in neural networks. 
#### In this question, you are asked to implement a softmax function that performs like the following:
\begin{equation*}
Softmax(x_i) = \frac{e^{x_i}}{\sum_{i=1}^N e^{x_i}}
\end{equation*}
#### where $x_i$ is the element inside the input vector $X$ such that $x_i \in X[x_0, x_1, x_2, \ldots, x_N]$, and $N$ is the total number of elements in vector $X$. 
#### Then, apply the softmax function to column 0 of iris dataset to calculate the softmax-converted vector of column 0. 

In [183]:
def softmax(np_vector):
    """
    This function takes a 1-D numpy array as the input,
    and outputs the transformed version of the input vector
    with softmax equation.
    
    Arguments:
        np_vector: 1-D numpy array
        
    Return:
        The transformed array with softmax equation.
    """
    expn = np.exp(np_vector)
    return expn / expn.sum()





In [184]:
# Test the function with column 0 as the input. 
arr = softmax(iris[:,:1])
print(arr.reshape(150,))

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

# Great Job!