<h1><center>DS 200 - Lec4: Numpy Arrays</center></h1>

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on Numpy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Numpy arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

In this lecture, we will learn the basics of Numpy, that is, creating a Numpy array.


## Preparations:

### Installation Instructions

**For most of you, Numpy has already been installed since Numpy package comes with Anaconda by default. If not, it is highly recommended you install Python using the Anaconda Individual Edition to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**


### Using NumPy

Once you've installed Numpy you can import it as a library:

In [6]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.
______

# Numpy Arrays

Numpy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## 1. Creating Numpy Arrays (ndarray)

### a. Converting from a Python List

We can create an array by directly converting a list or list of lists:

In [7]:
my_list = [1,2,3]
my_list

[1, 2, 3]

Use `np.array()` function to convert `my_list` to a ndarray vector.  

In [8]:
np.array(my_list)




array([1, 2, 3])

Given a list of list. 

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Use `np.array()` function to convert `my_matrix` to a ndarray matrix.  

In [10]:
np.array(my_matrix)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### b. Using Numpy Built-in Functions

There are lots of built-in ways to generate ndarrays

#### arange()

Return evenly spaced values within a given interval.

Try to generate all integers from 0 to 9, like the way we did with `list(range(10))`

In [11]:
np.arange(10)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Now, generate a ndarray of all even integers from 0 to 9.

In [12]:
np.arange(0, 11, 2)



array([ 0,  2,  4,  6,  8, 10])

#### zeros() and ones()

Generate arrays of zeros or ones with various sizes and shapes.

In [13]:
np.zeros((3))



array([0., 0., 0.])

In [14]:
np.zeros((5,5))



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)



array([1., 1., 1.])

In [16]:
np.ones((3,3))



array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace()
Return evenly spaced numbers over a specified interval.

In [19]:


np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

#### Exercise: generate 50 evenly spaced numbers over the range of 0 to 10. 

In [17]:
np.linspace(0, 100, 50)



array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

#### eye()

Create a 4x4 identity matrix

In [14]:
eye()



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### c. Generating random numbers for ndarrays.

Numpy also has lots of functions to create random-numbered arrays, by using the `random` module.

#### rand()
Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``. rand() assumes "uniform" distribution of the random numbers. 

Now, create a 1-D random vector that has a length of 2. Use seed 101. 

In [23]:
np.random.seed(101)
np.random.rand(2)


array([0.51639863, 0.57066759])

Now, create a 2-D random matrix with the size of 5x5. Use seed 101.

In [25]:
np.random.seed(101)
np.random.rand(5, 5)

array([[0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698],
       [0.83389686, 0.30696622, 0.89361308, 0.72154386, 0.18993895],
       [0.55422759, 0.35213195, 0.1818924 , 0.78560176, 0.96548322],
       [0.23235366, 0.08356143, 0.60354842, 0.72899276, 0.27623883],
       [0.68530633, 0.51786747, 0.04848454, 0.13786924, 0.18696743]])

In [34]:
np.random.seed(101)
np.random.rand() * 5 +10


12.581993138512232

#### randn()

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [39]:
np.random.seed(101)
np.random.randn(2)

array([2.70684984, 0.62813271])

In [41]:
np.random.seed(101)
np.random.randn(5, 5)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795],
       [-0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206],
       [ 0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722],
       [ 0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889],
       [ 0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072]])

#### randint()
Return random integers from `low` (inclusive) to `high` (exclusive). The third argument determines the number of random integers you need. 

In [42]:
np.random.seed(101)
np.random.randint(1, 100)

96

In [43]:
np.random.seed(101)
np.random.randint(1, 100, 10)



array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41])

## 2. Array Attributes and Methods

Let's discuss some useful attributes and methods for a ndarray:

In [44]:
np.random.seed(101)
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

print('arr: ', arr)
print('ranarr: ', ranarr)

arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
ranarr:  [31 11 17  6 23 11 47  9 13 40]


### a. reshape() method
Returns an array containing the same data with a new shape.

In [48]:
arr.reshape(5, 5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### b. max() ,min(), argmax(), argmin() methods

These are useful methods for finding max or min values. Or to find their index locations using argmin() or argmax().

In [49]:
ranarr.max()



47

In [50]:
ranarr.min()



6

In [51]:
ranarr.argmax()



6

In [52]:
ranarr.argmin()



3

### c. shape

Shape is an attribute that arrays have (not a method):

In [53]:
# Vector
arr.shape



(25,)

In [55]:
# Notice the two sets of brackets, 
# so it's a matrix (2D) rather than a vector (1D)
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [56]:
# Verify with shape
arr.reshape(1,25).shape


(1, 25)

In [57]:
# Reshape so that it is vertical 
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [58]:
# Reshape to the original
arr.reshape(25,)



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### d. dtype

You can also grab the data type of the object in the array:

In [59]:
arr.dtype



dtype('int32')

# Great Job!