# <center> DS 200 - Homework 2: Python and Numpy

## Introduction:

#### In this assignment, you are provided with some code snippets, and you are asked to complete the Python programs in each question. The programs are designed to give you practice with Python control flow, functions, list comprehension, lambda expression, useful Python functions and Numpy arrays. For function questions, you will need to remove the `pass` statement and edit the Python code accordingly to fulfill the functionality. 

## Q1 (10 points)

#### Implement the functions `arith1()`, `arith2()`, `arith3()`, and `arith4()` in the provided spaces. Feel free to insert new cells and test your program.

In [1]:
def arith1(x):
    """ 
    Given an integer number x, returns:
        1) 0, if x is negative or 0;
        2) x, if x is strictly positve and less than or equal to 10;
        3) 10, if otherwise 
    """
    if x<=0.0:
        num = 0.0
    elif (x> 0.0) & (x<= 10.0):
        num = x
    else:
        num = 10.0
    return num

#### Test case: if the result is `True`, that means your function passes the test cases. 

In [2]:
arith1(-99) == 0 and arith1(9.5) == 9.5 and arith1(10.5) == 10

True

In [3]:
def arith2(x, y):
    """
    Given two integer numbers x and y, returns:
        1) 2x + y, if x is strictly greater than y;
        2) 4y - 3, if y is strictly greater than x;
        3) x^3 + xy, if x is equal to y;
    """
    if x>y:
        temp = 2*x + y
    elif y>x:
        temp = 4*y-3
    elif x == y:
        temp = x**3 + x*y
    return temp

#### Test case: if the result is `True`, that means your function passes the test cases. 

In [4]:
arith2(5, 4) == 14 and arith2(3, 3) == 36 and arith2(3, 8) == 29

True

In [5]:
def arith3(x, y, z):
    """
    Given three integer numbers x, y, and z, returns:

        1) 0, if any of the two numbers are the same;
        2) 1, if the numbers are ordered such that x < y and y < z;
        3) 2, if otherwise;
    """
    if (x==y)|(x==z)|(y==z):
        num = 0
    elif (x<y)&(y<z):
        num = 1
    else:
        num = 2
    return num

#### Test case: if the result is `True`, that means your function passes the test cases. 

In [6]:
arith3(7, 8, 7) == 0 and arith3(3, 4, 5) == 1 and arith3(9, 9, 9) == 0 and arith3(9, 8, 7) == 2

True

In [7]:
def arith4(x, y, z, w):
    """ Given four integer numbers x, y, z, and w, returns:

        1) the maximum of arith2(x, y) and arith2(z, w), if x is strictly less than y;
        2) the sum of arith3(z, y, x) and arith1(w), if otherwise """
    if x<y:
        temp1 = arith2(x, y)
        temp2 = arith2(z, w)
        if temp1>temp2:
            num = temp1
        else:
            num = temp2
    else:
        num = arith3(z,y,x) + arith1(w)

    return num

#### Test case: if the result is `True`, that means your function passes the test cases. 

In [8]:
arith4(5,2,3,4) == 6 and arith4(2, 5, 3, 4) == 17

True

## Q2 (10 points)

#### Implement the functions `seq_add()` in the provided spaces. You are not allowed to use the Python math library in this question. Feel free to insert new cells and test your program.

In [81]:
def seq_add(start, end, k):
    """ 
    The function takes three arguments: start, end and k,
    and returns the sum of every k-th number between start and end. 
    Assume start <= end and k > 0.
    
    For example:
        seq_add(1, 10, 3) returns 1 + 4 + 7 + 10 = 22
        seq_add(1, 11, 3) returns 1 + 4 + 7 + 10 = 22
        seq_add(1, 5, 6) returns 1
        seq_add(4, 9, 2) returns 4 + 6 + 8 = 18
        seq_add(7, 7, 3) returns 7
        seq_add(-4, 8, 5) returns -4 + 1 + 6 = 3

    """
    if start == end:
        return start
    else:
        num = start
        temp = k
        for i in range(start+k, end+1, k):
            num+=i                       
    return num

#### Test case: if the result is `True`, that means your function passes the test cases. 

In [83]:
seq_add(1, 10, 3) == 22 and seq_add(1, 11, 3) == 22 and seq_add(1, 5, 6) == 1 and \
seq_add(4, 9, 2) == 18 and seq_add(7, 7, 3) == 7 and seq_add(-4, 8, 5) == 3

True

#### Implement the functions fact() in the provided spaces. You are not allowed to use the Python math library in this question. Feel free to insert new cells and test your program.

In [11]:
def fact(n):
    """ 
    This function takes an integer n as an input, and 
    returns n!, the factorial of n.  
    If n <= 0, function returns 0.  
    
    For example:
        fact(5) returns 5 * 4 * 3 * 2 * 1 = 120
        fact(-2) returns 0
    """
    if n <= 0:
        ans = 0
    else:
        ans = 1
        for i in range(1,n+1):
            ans *=i
            
    return ans

#### Test case: if the result is `True`, that means your function passes the test cases. 

In [12]:
fact(5) == 120 and fact(-2) == 0 and fact(19) == 121645100408832000

True

## Q3 (10 points)

#### Implement the `word_counter()` function that counts the number of occurrences of each word from a given text. The function returns the word counts in a dictionary format. This function is NOT case insensitive, e.g. "This" and "this" should be treated as the same word. 

Sample input:  
```
This is a common message for people this message is private and circulate this with caution  
```

In [11]:
def word_counter(text_msg):
    """
    Counts the number of occurrence of words from the input argument, returns word counts in a dictionary
    """
    counts = dict()
    words = text_msg.split()
    for word in words:
        if word in counts:
            counts[word.lower()] += 1
        else:
            counts[word.lower()] = 1
    
    return counts

#### Test case

In [12]:
message = 'This is a common message for people this message is private and circulate this with caution'
word_counter(message)

{'this': 3,
 'is': 2,
 'a': 1,
 'common': 1,
 'message': 2,
 'for': 1,
 'people': 1,
 'private': 1,
 'and': 1,
 'circulate': 1,
 'with': 1,
 'caution': 1}

## Q4 (20 points)

#### You are given an accounting routine used in the Etown's bookstore. The data is stored in a nested list, which looks like the following. 

| Order Number  | Book Title and Author             | Quantity | Price per Item |
| ------------- |:---------------------------------:| --------:| ---------------|
| 34587         | Learning Python, Mark Lutz        | 4        | 40.95          |
| 98762         | Programming Python, Mark Lutz     | 5        | 56.80          |
| 77226         | Head First Python, Paul Barry     | 3        | 32.95          |
| 88112         | Einführung in Python3, Bernd Klein| 3        | 24.99          |

#### Use `map()` function with lambda expression to return a list of 2-tuples. A 2-tuple is a tuple that has two elements. For example:

```[('34587', 163.8), ('98762', 284.0), ('77226', 103.85000000000001), ('88112', 79.97)]```

#### In each 2-tuple, the first element represents the order number of a book, and the second element represents the `total value of the order` (unit price of a book * book quantity). Just to make the question a bit more "interesting", the total value of the order should be increased by 5 if the total value of the order is less than 110. 

Hint: breakdown the question into two steps. The first step is the half without needing to add a 5 to the total value. Then in the second step, take the result from step 1 as the input to get the final solution. Note you need to use map() function more than once in this question. 

In [13]:
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

In [147]:
mylist = list(map(lambda rec: (rec[0], (rec[2] * rec[3])), orders))

output = list(map(lambda tup: (tup[0], tup[1] + 5) if tup[1] <110 else tup, mylist))





print(output)

[('34587', 163.8), ('98762', 284.0), ('77226', 103.85000000000001), ('88112', 79.97)]


## Q5 (50 points)

#### 1. Assume we have 15 students taking turns to roll a six-sided die. Each student will roll a die for 10 times. Generate a Numpy array called `games` that presents the result of the game. Assume rows represent the students and columns represent 10 turns. Use random seed as 101.

|            | Turn 0 | Turn 1 | Turn 2 | ... | Turn 9 |
|-----------:|--------|--------|--------|-----|--------|
|  Student 0 | 3      | 5      | 1      |     | 4      |
|  Student 1 | 2      | 3      | 1      |     | 6      |
|  Student 2 | 6      | 4      | 3      |     | 3      |
|        ... |        |        |        |     |        |
| Student 14 | 2      | 5      | 4      |     | 2      |

In [32]:
# Run this cell to import numpy
import numpy as np

In [71]:
np.random.seed(101)
games = np.random.randint(1,7,size=(15,10))







# Show the array games
games

array([[4, 2, 6, 4, 2, 6, 1, 5, 1, 6],
       [5, 5, 1, 6, 5, 6, 1, 2, 4, 3],
       [1, 4, 6, 4, 4, 3, 5, 1, 2, 4],
       [3, 5, 4, 1, 2, 2, 1, 5, 4, 4],
       [5, 3, 5, 1, 2, 5, 3, 5, 1, 5],
       [3, 5, 2, 1, 4, 4, 2, 6, 1, 5],
       [5, 4, 3, 4, 3, 4, 5, 5, 4, 1],
       [3, 3, 4, 6, 2, 6, 6, 3, 3, 3],
       [5, 4, 4, 3, 2, 4, 5, 4, 4, 5],
       [3, 6, 2, 5, 6, 1, 4, 1, 4, 6],
       [6, 5, 5, 4, 3, 4, 3, 2, 6, 4],
       [5, 6, 6, 6, 3, 6, 2, 4, 5, 5],
       [4, 4, 6, 2, 2, 3, 6, 4, 1, 2],
       [5, 6, 6, 2, 1, 5, 1, 5, 5, 3],
       [6, 5, 6, 4, 1, 4, 6, 2, 1, 5]])

#### 2. Show the numbers from `Turn 2` for all students.

In [72]:
games[:, 2]



array([6, 1, 6, 4, 5, 2, 3, 4, 4, 2, 5, 6, 6, 6, 6])

#### 3. Show the numbers for the last three turns for the first three students.

In [73]:
games[:3,7:]



array([[5, 1, 6],
       [2, 4, 3],
       [1, 2, 4]])

#### 4. Show the numbers for `Turn 0`, `Turn 4` and `Turn 8` for `Student 1`, `Student 10` and `Student 14`.

In [74]:
games[[1,10,14]][:,[0,4,8]]



array([[5, 5, 4],
       [6, 3, 6],
       [6, 1, 1]])

#### 5. Find which student ID has the largest accumulated numbers over 10 turns. To receive full credits, you need to use existing Numpy methods and ufunc, and avoid using your own hands or loops. 

In [75]:
maxSum = [sum(i) for i in games]

maxSum.index(max(maxSum))

11

#### 6. Find which turn number has the smallest average number from all 15 students. To receive full credits, you need to use existing Numpy methods and ufunc, and avoid using your own hands or loops. 

In [97]:
means = np.mean(games, axis = 0)

In [151]:
np.where(means == means.min())

(array([4], dtype=int64),)

#### 7. Assume the following weights (importance) for each turn. How to get the weighted average numbers for all the students?

In [103]:
# Execute this line to have it in your workspace. 

weights = [0.1, 0.1, 0.1, 0.05, 0.05, 0.05, 0.15, 0.15, 0.15, 0.1]

In [104]:
games.dot(weights)



array([3.45, 3.3 , 3.25, 3.35, 3.55, 3.3 , 3.95, 3.8 , 4.2 , 3.65, 4.2 ,
       4.6 , 3.6 , 4.05, 4.  ])

#### 8. Find the student IDs that rolled number 6 for more than two times (including two).

In [143]:
for i in range(len(games)):
    filt = (games[i]==6)
    if filt.sum() >1:
        print(i)






0
1
7
9
10
11
12
13
14


#### 9. Duplicate the last two turns (`Turn 8` and `Turn 9`) from array `games` and add them as two additional turns to the end of the array. The newly generated array should be named as `games_new` and the original array `games` should stay intact. 

Hint: study the use of the `np.hstack()` and `np.vstack()` functions. 

In [148]:
col8and9 = games[:,[8,9]]
games_new = np.hstack((games, col8and9.copy()))








# Display arrays game and games_new
print('Original array:\n', games)
print('New array:\n', games_new)

Original array:
 [[4 2 6 4 2 6 1 5 1 6]
 [5 5 1 6 5 6 1 2 4 3]
 [1 4 6 4 4 3 5 1 2 4]
 [3 5 4 1 2 2 1 5 4 4]
 [5 3 5 1 2 5 3 5 1 5]
 [3 5 2 1 4 4 2 6 1 5]
 [5 4 3 4 3 4 5 5 4 1]
 [3 3 4 6 2 6 6 3 3 3]
 [5 4 4 3 2 4 5 4 4 5]
 [3 6 2 5 6 1 4 1 4 6]
 [6 5 5 4 3 4 3 2 6 4]
 [5 6 6 6 3 6 2 4 5 5]
 [4 4 6 2 2 3 6 4 1 2]
 [5 6 6 2 1 5 1 5 5 3]
 [6 5 6 4 1 4 6 2 1 5]]
New array:
 [[4 2 6 4 2 6 1 5 1 6 1 6]
 [5 5 1 6 5 6 1 2 4 3 4 3]
 [1 4 6 4 4 3 5 1 2 4 2 4]
 [3 5 4 1 2 2 1 5 4 4 4 4]
 [5 3 5 1 2 5 3 5 1 5 1 5]
 [3 5 2 1 4 4 2 6 1 5 1 5]
 [5 4 3 4 3 4 5 5 4 1 4 1]
 [3 3 4 6 2 6 6 3 3 3 3 3]
 [5 4 4 3 2 4 5 4 4 5 4 5]
 [3 6 2 5 6 1 4 1 4 6 4 6]
 [6 5 5 4 3 4 3 2 6 4 6 4]
 [5 6 6 6 3 6 2 4 5 5 5 5]
 [4 4 6 2 2 3 6 4 1 2 1 2]
 [5 6 6 2 1 5 1 5 5 3 5 3]
 [6 5 6 4 1 4 6 2 1 5 1 5]]


#### 10. Suppose we need to change the die used for `games_new` from a 6-sided die to a 20-sided one. 

<img src="https://img1.cgtrader.com/items/874879/95c1e35d3c/dice-6-sided-and-20-sided-3d-model-low-poly-ma-mb.jpg" alt="dice" width="250"/>

#### Now we need to apply a linear projection for each number from the range of [1,6] to [1,20]. The linear project should follow the following equation:

```
f(x) = floor( x * 20 / 6) - A
```

#### where x means the original number from the 6-sided die. `floor()` is a function that outputs the greatest integer less than or equal to the given input to the function. And `A `represents a random integer in the range of [0, 2] (all inclusive). Use random seed 101. Note: `A` needs to be a new random number for each projection. 

In [149]:
np.random.seed(101)
for i in range(len(games_new)):
    for n in range(len(games_new[0])):
        A = np.random.randint(0,3)
        games_new[i][n] = np.floor(((games_new[i][n])*20/6)) - A
print(games_new)




[[12  4 19 12  5 20  3 16  2 20  3 20]
 [14 15  3 19 16 19  1  6 12  8 13 10]
 [ 2 11 18 13 13  9 15  3  4 13  6 11]
 [10 16 11  1  5  6  1 16 13 13 11 13]
 [15 10 15  2  6 16 10 14  1 14  3 16]
 [10 14  4  1 11 11  5 18  2 15  2 14]
 [14 11 10 11  9 11 16 16 11  1 12  2]
 [10  9 13 18  6 19 18  9 10 10  8  8]
 [15 12 11  8  6 12 14 12 11 15 11 15]
 [ 9 18  4 16 20  2 12  1 12 18 12 18]
 [20 14 15 13  9 12  9  6 20 13 20 13]
 [14 19 20 19 10 19  5 13 16 14 14 15]
 [12 13 19  6  6 10 19 11  1  6  2  4]
 [16 20 18  6  1 14  1 16 14  8 15  9]
 [18 15 18 13  1 13 18  5  2 15  2 14]]


# Great job!